language: node_js
node_js:
- '0.10'
before_install:
- wget https://github.com/spf13/hugo/releases/download/v0.14/hugo_0.14_linux_amd64.tar.gz -O /tmp/hugo.tar.gz
- tar -xvf /tmp/hugo.tar.gz
- mv hugo_0.14_linux_amd64/hugo_0.14_linux_amd64 hugo_0.14_linux_amd64/hugo
- export PATH=$PATH:$PWD/hugo_0.14_linux_amd64
- 'echo -e {\\n    \"content\" :\\n    {\\n        \"root\" : \"$PWD\"\\n    }\\n}  > config.json'
- export CONFIG_JSON=$PWD/config.json
- git clone https://github.com/cloudify-cosmo/docs.getcloudify.org-site.git
install:
- npm install -g bower
- npm install -g grunt-cli
- cd docs.getcloudify.org-site
- bower install
- npm install
script:
- >
  regex_version='^([0-9]+\.[0-9]+\.[0-9]+)-build$'

  if [[ $TRAVIS_PULL_REQUEST != true ]] ;then
    if [[ $TRAVIS_BRANCH == "master" ]] ;then
      export REDIRECT_VERSION=$(<$HOME/build/cloudify-cosmo/docs.getcloudify.org/redirect_version)
      export DOCS_SITE_BASE_URL="http://docs.getcloudify.org/latest"
    elif [[ $TRAVIS_BRANCH =~ $regex_version ]] ;then
      export DOCS_VERSION=${BASH_REMATCH[1]}
      export DOCS_SITE_BASE_URL="http://docs.getcloudify.org/$DOCS_VERSION}"
    else
      export DOCS_SITE_BASE_URL="http://stage-docs.getcloudify.org/$TRAVIS_BRANCH/"
    fi
  fi

  echo redirect_version: $REDIRECT_VERSION
  echo baseurl: $DOCS_SITE_BASE_URL
- grunt build
deploy:
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJZWYILFE5EERNQ6A
  secret_access_key:
    secure: XiEdtf3cr6JnnHZ03lkyD3D/h4zPwNZDvX63CxVpw/3V80CtgiXKZW7Qo0J7z0RDu4wSymmEEc7S84Uov2NBZ13Wzi/z8e865djW+MVo8sOiRUtNo82hF7jyKQkIIIA2GtOR5h5mgY4vaoaN9/vto9rerN//mwRqb71aNwwyEuXPXupjdRSrXgOVSo+6K/FoRneyBhu6dd9XtsFFm9BFS6KRFzVCVX5An1I9WDQEsmJyfeBDRQOQWRITVcBog+lO0QT/QenyjMcMC1/UGxeUVRIh/n2JwBB5xNQyZm9WFOXqrTCZlUQuaJSZADQwdiVnJsufAaI20/ZR5E0mxcWFurJP+U7obYFvcxoWBYxU/F15x66lc34ew8g5FDGgi5uThG5ObO+jcYoNnXoSOASHBQqEVrxOvNj/oiAUFp4y/dy3N4QO59MASFM0GUk+AdCgcezbPu4lGT9UXE00pbIrHoQN8Q/HwP5dC1+dIiMOmctN0CQbujsvytO+Vbf6LlCGIfy4ADbZSdqU5SajU2+zKmBH3skkJ0oRMD1Nmn0KFFcF73jprUWcAjZPrZi+FMmGuJo++DH2YGijvnQYmPJFUJNbaEQKCZrdWftmiQN26lXvAjpaKi/x4KaCT1U4Vf/klbCgKNT8RdqzYyaun6iFM7zbAWcj3YKMp9FK3spi9DY=
  bucket: docs.getcloudify.org
  local_dir: public
  upload_dir: latest
  acl: public_read
  on:
    repo: cloudify-cosmo/docs.getcloudify.org
    branch: master
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJZWYILFE5EERNQ6A
  secret_access_key:
    secure: XiEdtf3cr6JnnHZ03lkyD3D/h4zPwNZDvX63CxVpw/3V80CtgiXKZW7Qo0J7z0RDu4wSymmEEc7S84Uov2NBZ13Wzi/z8e865djW+MVo8sOiRUtNo82hF7jyKQkIIIA2GtOR5h5mgY4vaoaN9/vto9rerN//mwRqb71aNwwyEuXPXupjdRSrXgOVSo+6K/FoRneyBhu6dd9XtsFFm9BFS6KRFzVCVX5An1I9WDQEsmJyfeBDRQOQWRITVcBog+lO0QT/QenyjMcMC1/UGxeUVRIh/n2JwBB5xNQyZm9WFOXqrTCZlUQuaJSZADQwdiVnJsufAaI20/ZR5E0mxcWFurJP+U7obYFvcxoWBYxU/F15x66lc34ew8g5FDGgi5uThG5ObO+jcYoNnXoSOASHBQqEVrxOvNj/oiAUFp4y/dy3N4QO59MASFM0GUk+AdCgcezbPu4lGT9UXE00pbIrHoQN8Q/HwP5dC1+dIiMOmctN0CQbujsvytO+Vbf6LlCGIfy4ADbZSdqU5SajU2+zKmBH3skkJ0oRMD1Nmn0KFFcF73jprUWcAjZPrZi+FMmGuJo++DH2YGijvnQYmPJFUJNbaEQKCZrdWftmiQN26lXvAjpaKi/x4KaCT1U4Vf/klbCgKNT8RdqzYyaun6iFM7zbAWcj3YKMp9FK3spi9DY=
  bucket: docs.getcloudify.org
  local_dir: public
  upload_dir: $DOCS_VERSION
  acl: public_read
  on:
    all_branches: true
    condition: "^[0-9]+\.[0-9]+\.[0-9]+-build$ =~ $TRAVIS_BRANCH"
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJAV4DLHK3N32UZAQ
  secret_access_key:
    secure: bA6kunRAIxOw0JD/Z+9ZzVsaRFdl6Z8yfXMAipjvAw9M4xWz7xh6KGzHrZe2kZC8sYyeAwc7jqiI5bgVSHIjoH6ZdPB4xvNQrXYa1ShZCyYUgl8w6j3kUAgB+kYXz5jL0+bZGSK7pGmmK/sMfqVI10xGvKTRmqi5uMmO3O5NLim736jsZB/qvju6ibrszslNDcS/Kk8ssUGWUwOkrM8V/L4bWO/5rhvTxbKktyIV8preKHlmrMZML0Hn5fUaAdygmUMYqmj0NLdV1pBzkSX2cLK4nL+SefOBLTWn7+Xd45/yqHs66XrP65pZIdYxmhna0v5c4Z/lfai27gKNMktrMkqpNfJWAbGiIUOF6cNG6dRaHqdgjsB2tKzbUiX3kGs6E4KV1NLCV8Iq/kEfFNyku7lLuoUOaj8r8LG4k+wKwJpjr24Fnpi8nfgSuP0QW+6WmqcM/H9LTIhfjajScgr1s1E5T4wNHo23xli0ewVqqE5CE3vIvikbjlRGDJuuKZBe6GevRUvFsYSq3QgfjsMuEG/29JRjUZvpritfX9clNVFXXrjnJ9KO5fUB8CiyvuBtuj8PO6F1izWGHQImn0Dd94ZZH1cbeuSh7EWEEmUPnXgzdvR61zXeWb0js4JDYeFzgNpMEWZ7CzYi7c6aCLkdmHipz5fgX0k94o24LEnzeOg=
  bucket: stage-docs.getcloudify.org
  local_dir: public
  upload-dir: $TRAVIS_BRANCH
  acl: public_read
  region: eu-west-1
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
